[package]
name = "mini_db"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["canvas", "tokio"] }
iced_aw = { version = "0.14.1", features = ["spinner"] }
sqlx = { version = "0.8.6", features = [
  "runtime-tokio",
  "sqlite",
  "macros",
  "migrate",
] }
tokio = { version = "1.52.3", features = ["full"] }
dotenvy = "0.15.7"
serde = "1.0.228"
rand = "0.10.1"
serde_json = "1.0.149"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
